### ISSUE TITLE
FormMaps.init problem

### ISSUE THREAD

**Issue by Nighthawk11120** [adamped/XamarinMaps#1]
For some reason on the sample project when I search for the FormMaps.init it is not in the project.  I am supposed to put in my authentication token for the windows phone to make the Bing maps work.

Any help would be very much appreciated

Thanks in advanced

**Comment by adamped** [comment]
The FormMaps.Init is located here: https://github.com/adamped/XamarinMaps/blob/master/XamarinMaps/XamarinMaps.UWP/App.xaml.cs for UWP. 

You can enter your Bing Auth Key there.

**Comment by Nighthawk11120** [comment]
Thanks. 
Where in this code file should I put my Bing Auth key?

Also do you know what I can do to fix the caution symbol on the Bing maps for C#,C++ or Visual Basic and Microsoft Visual C++ 2013 runtime package for windows (under the windows phone?

![image](https://user-images.githubusercontent.com/27147259/34902343-9dbafade-f7e7-11e7-89a0-c480b0556092.png)

Thanks in advanced

Scott

**Comment by adamped** [comment]
You have to go to Tools > Extensions and Updates and download the Bing Extensions.
Remove the C++ runtime, and then add a reference, and find it again to re-add it. It's likely you just have a slightly different version than that project.

The Bing Auth Key should be in  FormMaps.Init("AUTH KEY");

**Comment by Nighthawk11120** [comment]
When I try to install the packages it says that the extension is not compatible with visual studio 2017

**Comment by adamped** [comment]
You probably need to find a newer version of it. 2013 is rather old. Think you use 2015 at least these days.

**Comment by Nighthawk11120** [comment]
Do I just paste the Bing Auth key anywhere on the bottom of the  FormsMaps.Init( );?
![image](https://user-images.githubusercontent.com/27147259/34902566-347634bc-f7ec-11e7-81ab-d9377f7c368e.png)

and what 2015 one should I reference the one in the blue or red arrow?
![image](https://user-images.githubusercontent.com/27147259/34902564-15a236bc-f7ec-11e7-9dab-053c34d1c40a.png)

Also I don't see a reference that I can add for Bing maps

**Comment by adamped** [comment]
For the Bing Maps, you need to download the extension first from Tools > Extensions and Updates in Visual Studio.

The Bing Auth Key should be a parameter for the Init function.

**Comment by Nighthawk11120** [comment]
ok I downloaded bing maps but it wont let me reference it.

**Comment by Nighthawk11120** [comment]
what do you mean by making a parameter for the Init function?
