### ISSUE TITLE
Bindable Properties and Custom Renderers

### ISSUE THREAD

**Issue by jimwallery** [adamped/XamarinMaps#2]
Thank you for the Xamarin Forms Maps with Bindable Properties post.  I found it to be extremely helpful for a sandbox app that I am creating related to mapping with mvvm.   In the last section of the post you refer to incorporating custom map renderers but I am looking for a little further guidance on whether you can shift the bindablemap into the custom map renderer or should the bindings be incorporated directly into the custom map renderer.  Any thoughts would be much appreciated.  Thank you.

**Comment by adamped** [comment]
The BindableMap is just extending the current XF Map control and adding an additional property. You don't need any custom renderer for this.

If you want to use a custom renderer as well, you can create one for the BindableMap and inherit from the existing MapRenderer, if you need to do platform specific changes to each map.
